version: '3'
services:

  quiz_nginx:
    container_name: 'quiz_nginx'
    image: nginx:stable-alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    depends_on:
      - quiz_app

  quiz_app:
    container_name: 'quiz_app'
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./:/var/www/app
    depends_on:
      - quiz_postgres
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "1"
      APP_SECRET: "<secret>"
      DATABASE_URL: "pgsql://app:app@quiz_postgres/app"

  quiz_postgres:
    container_name: 'quiz_postgres'
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "app"
      POSTGRES_PASSWORD: "app"
      POSTGRES_USER: "app"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
